version: '3'

services: 

  api:
    container_name: flask_api
    restart: on-failure
    build: ./api
    volumes: ['./api:/api']
    networks:
      - apinetwork

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
      - apinetwork
    expose:
      - "8080"
    ports:
      - "8080:8080"

  react:
    container_name: react_frontend
    restart: always
    build: ./wild_magic-frontend
    ports:
      - '80:80'

networks:
  apinetwork:
    driver: bridge
